name: Nightly workflow tests
on:
 # Uncomment these two lines for debugging, but leave them commented on 'main'
 pull_request:
   branches: [ main ]
 schedule:
 # 05:00 UTC = 06:00 CET = 07:00 CEST
 - cron: "0 5 * * *"

jobs:
  nightly:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: "3.9"

    - name: Install dev dependencies
      run: |
        pip install --upgrade pip wheel
        pip install -e .[tests]

    - name: Download MAGICC
      run: |
        wget -P bin/magicc/ ${{ secrets.MAGICC_TAR }}
        mkdir bin/magicc/magicc-v7.5.3
        tar -xf bin/magicc/magicc-v7.5.3.tar.gz -C bin/magicc/magicc-v7.5.3
        cp -r bin/magicc/magicc-v7.5.3/run/defaults/* bin/magicc/magicc-v7.5.3/run/
        MAGICC_RUN_DIR=bin/magicc/magicc-v7.5.3/run/ python scripts/generate-magicc-sr15-input-files.py
        wget -O data/magicc-drawnsets/magicc-drawnset.json ${{ secrets.MAGICC_DRAWNSET }}

    - name: Test with pytest
      env:
        MAGICC_EXECUTABLE_7: /home/runner/work/climate-assessment-dev/climate-assessment-dev/bin/magicc/magicc-v7.5.3/bin/magicc
        MAGICC_WORKER_NUMBER: 4
        MAGICC_WORKER_ROOT_DIR: /tmp
      run: |
          MAGICC_PROBABILISTIC_FILE=data/magicc-drawnsets/magicc-drawnset.json pytest tests -m nightly -r a -vv

    - name: Test run with .env only
      run: |
          echo "MAGICC_EXECUTABLE_7=${PWD}/bin/magicc/magicc-v7.5.3/bin/magicc" > .env
          echo "MAGICC_WORKER_NUMBER=4" >> .env
          echo "MAGICC_WORKER_ROOT_DIR=/tmp" >> .env

          MAGICC_PROBABILISTIC_FILE=data/magicc-drawnsets/magicc-drawnset.json pytest tests/nightly/test_workflow_nightly.py -m nightly -r a -vv
